'use strict';
/**
 * pdf.service.js — Generates PDF accessibility report using PDFKit
 */

const PDFDocument = require('pdfkit');
const fs          = require('fs');
const path        = require('path');

async function generatePDF(record) {
  const dir = path.join(__dirname, '..', '..', '..', 'shared', 'reports');
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });

  const filePath = path.join(dir, `accessibility-${record._id}.pdf`);

  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: 'A4' });
    const stream = fs.createWriteStream(filePath);
    doc.pipe(stream);

    const C = { primary: '#1a1a2e', accent: '#e94560', green: '#27ae60', orange: '#f39c12', red: '#e74c3c', gray: '#7f8c8d', light: '#ecf0f1' };

    /* ── Cover ── */
    doc.rect(0, 0, 595, 200).fill(C.primary);
    doc.fontSize(28).fillColor('#ffffff').text('WebAuditX', 50, 60);
    doc.fontSize(16).fillColor(C.accent).text('Accessibility & WCAG Compliance Report', 50, 100);
    doc.fontSize(11).fillColor('#aaaacc').text(`URL: ${record.url}`, 50, 135);
    doc.fontSize(10).fillColor('#aaaacc').text(`Generated: ${new Date().toLocaleString()}`, 50, 155);

    /* Score badge */
    const scoreColor = record.overallScore >= 80 ? C.green : record.overallScore >= 60 ? C.orange : C.red;
    doc.circle(500, 100, 45).fill(scoreColor);
    doc.fontSize(28).fillColor('#ffffff').text(`${record.overallScore}`, 470, 80, { width: 60, align: 'center' });
    doc.fontSize(10).fillColor('#ffffff').text('/ 100', 473, 113, { width: 60, align: 'center' });

    doc.moveDown(8);

    /* ── Summary ── */
    section(doc, 'Executive Summary', C.primary);
    const s = record.summary;
    const cols = [
      ['WCAG Level', record.wcagLevel],
      ['Total Issues', s.totalIssues],
      ['Critical', s.criticalIssues],
      ['Serious', s.seriousIssues],
      ['Passed Checks', `${s.passedChecks}/${s.totalChecks}`],
    ];
    cols.forEach(([label, value], i) => {
      const x = 50 + (i % 3) * 165;
      const y = doc.y + (i > 2 ? 60 : 0);
      if (i === 3) doc.moveDown(0.5);
      doc.rect(x, doc.y - 5, 150, 50).fill(C.light);
      doc.fontSize(10).fillColor(C.gray).text(label, x + 8, doc.y);
      doc.fontSize(20).fillColor(C.primary).text(String(value), x + 8, doc.y - 2);
      if (i % 3 !== 2) doc.moveUp(2.5);
    });
    doc.moveDown(4);

    /* ── Metric Scores ── */
    section(doc, 'Metric Breakdown', C.primary);
    const metrics = record.metrics || {};
    Object.entries(metrics).forEach(([, m]) => {
      if (!m || !m.name) return;
      const barW = Math.round((m.score / 100) * 300);
      const barColor = m.score >= 80 ? C.green : m.score >= 60 ? C.orange : C.red;
      const y = doc.y;
      doc.fontSize(10).fillColor(C.primary).text(`${m.name}`, 50, y, { width: 200 });
      doc.rect(255, y + 2, 300, 12).fill(C.light);
      doc.rect(255, y + 2, barW, 12).fill(barColor);
      doc.fontSize(10).fillColor(C.gray).text(`${m.score}/100`, 565, y, { width: 40, align: 'right' });
      doc.moveDown(1.2);
    });

    /* ── Issues ── */
    if (doc.y > 650) doc.addPage();
    section(doc, 'Issues Found', C.primary);
    (record.issues || []).forEach((issue, idx) => {
      if (doc.y > 700) doc.addPage();
      const impactColor = issue.impact === 'critical' ? C.red : issue.impact === 'serious' ? C.orange : C.orange;
      doc.rect(50, doc.y, 495, 1).fill(C.light);
      doc.moveDown(0.5);
      doc.fontSize(11).fillColor(impactColor).text(`[${issue.impact?.toUpperCase()}] `, 50, doc.y, { continued: true });
      doc.fillColor(C.primary).text(`${issue.rule} — WCAG ${issue.wcag}`);
      doc.fontSize(9).fillColor(C.gray).text(issue.description || '', 60, doc.y, { width: 480 });
      doc.fontSize(9).fillColor(C.green).text(`Fix: ${issue.fix || ''}`, 60, doc.y, { width: 480 });
      doc.moveDown(0.8);
    });

    /* ── AI Report ── */
    if (record.aiReport) {
      if (doc.y > 600) doc.addPage();
      section(doc, 'AI-Generated Analysis', C.primary);
      const cleanReport = record.aiReport.replace(/[#*`]/g, '').trim();
      doc.fontSize(10).fillColor('#333333').text(cleanReport, 50, doc.y, { width: 495, lineGap: 4 });
    }

    /* ── Footer ── */
    doc.addPage();
    doc.rect(0, doc.page.height - 60, 595, 60).fill(C.primary);
    doc.fontSize(10).fillColor('#aaaacc').text(
      'Generated by WebAuditX — Accessibility & WCAG Compliance Module',
      50, doc.page.height - 38, { align: 'center', width: 495 }
    );

    doc.end();
    stream.on('finish', () => resolve(filePath));
    stream.on('error', reject);
  });
}

function section(doc, title, color) {
  doc.moveDown(0.5);
  doc.rect(50, doc.y, 495, 28).fill(color);
  doc.fontSize(13).fillColor('#ffffff').text(title, 58, doc.y - 22);
  doc.moveDown(1.5);
}

module.exports = { generatePDF };