'use strict';
const mongoose = require('mongoose');

const IssueSchema = new mongoose.Schema({
  id:          { type: String },
  title:       { type: String, required: true },
  description: { type: String, required: true },
  detail:      { type: String, default: '' },
  element:     { type: String, default: null },
  device:      { type: String, enum: ['mobile', 'tablet', 'both', 'all'], default: 'mobile' },
  severity:    { type: String, enum: ['critical', 'medium', 'low'], required: true },
  category:    { type: String, default: 'general' },
  impact:      { type: String, default: '' },
  howToFix:    { type: String, default: '' },
  affectedCount: { type: Number, default: 0 },
  source:      { type: String, default: 'manual' },
}, { _id: false });

const MobileFriendlinessSchema = new mongoose.Schema({
  url: { type: String, required: true, trim: true },

  /* ── Raw scores per data source ── */
  apiResults: {
    pageSpeed: {
      available:         { type: Boolean, default: false },
      performanceScore:  { type: Number, default: null },
      accessibilityScore:{ type: Number, default: null },
      seoScore:          { type: Number, default: null },
      bestPracticesScore:{ type: Number, default: null },
      fcp:  { type: String, default: null },
      lcp:  { type: String, default: null },
      tti:  { type: String, default: null },
      tbt:  { type: String, default: null },
      cls:  { type: Number, default: null },
      si:   { type: String, default: null },
      fid:  { type: String, default: null },
      ttfb: { type: String, default: null },
      rawAudits: { type: mongoose.Schema.Types.Mixed, default: {} },
    },
    moz: {
      available:    { type: Boolean, default: false },
      domainAuthority: { type: Number, default: null },
      pageAuthority:   { type: Number, default: null },
      spamScore:       { type: Number, default: null },
      linkingDomains:  { type: Number, default: null },
    },
    manual: {
      available:         { type: Boolean, default: true },
      hasViewportMeta:   { type: Boolean, default: false },
      viewportContent:   { type: String, default: '' },
      hasResponsiveCSS:  { type: Boolean, default: false },
      hasMediaQueries:   { type: Boolean, default: false },
      hasTouchIcons:     { type: Boolean, default: false },
      hasAmpVersion:     { type: Boolean, default: false },
      hasServiceWorker:  { type: Boolean, default: false },
      isHttps:           { type: Boolean, default: false },
      pageLoadSize:      { type: Number, default: 0 },
      imageCount:        { type: Number, default: 0 },
      unoptimizedImages: { type: Number, default: 0 },
      hasLazyLoading:    { type: Boolean, default: false },
      totalLinks:        { type: Number, default: 0 },
      brokenLinks:       { type: Number, default: 0 },
      hasStructuredData: { type: Boolean, default: false },
      hasOpenGraph:      { type: Boolean, default: false },
      titleLength:       { type: Number, default: 0 },
      metaDescLength:    { type: Number, default: 0 },
      h1Count:           { type: Number, default: 0 },
      fontCount:         { type: Number, default: 0 },
      renderBlocking:    { type: Number, default: 0 },
      inlineStyles:      { type: Number, default: 0 },
    },
  },

  /* ── Structured metrics ── */
  mobileMetrics: {
    responsive: {
      hasViewportMeta:   { type: Boolean, default: false },
      viewportCorrect:   { type: Boolean, default: false },
      hasMediaQueries:   { type: Boolean, default: false },
      hasFlexOrGrid:     { type: Boolean, default: false },
      mobileLayoutScore: { type: Number, default: 0 },
      overflowIssues:    { type: Number, default: 0 },
      stackingIssues:    { type: Number, default: 0 },
      brokenLayouts:     { type: Number, default: 0 },
    },
    readability: {
      avgFontSize:        { type: Number, default: 0 },
      smallFontCount:     { type: Number, default: 0 },
      lineSpacingOk:      { type: Boolean, default: false },
      contrastIssues:     { type: Number, default: 0 },
      fontLoadPerformance:{ type: String, default: 'unknown' },
    },
    tapTargets: {
      totalTargets:     { type: Number, default: 0 },
      smallTargets:     { type: Number, default: 0 },
      overlappingCount: { type: Number, default: 0 },
      passRate:         { type: Number, default: 100 },
      tapTargetScore:   { type: Number, default: 100 },
    },
    touchGestures: {
      pinchZoomEnabled:  { type: Boolean, default: true },
      smoothScrolling:   { type: Boolean, default: true },
      touchEventsOk:     { type: Boolean, default: true },
      blockedGestures:   { type: [String], default: [] },
    },
    navigation: {
      hasMobileMenu:     { type: Boolean, default: false },
      hasHamburger:      { type: Boolean, default: false },
      navigationDepth:   { type: Number, default: 0 },
      menuClarity:       { type: String, default: 'unknown' },
      hasSkipLinks:      { type: Boolean, default: false },
    },
    performance: {
      performanceScore:       { type: Number, default: null },
      firstContentfulPaint:   { type: String, default: null },
      largestContentfulPaint: { type: String, default: null },
      timeToInteractive:      { type: String, default: null },
      totalBlockingTime:      { type: String, default: null },
      cumulativeLayoutShift:  { type: Number, default: null },
      speedIndex:             { type: String, default: null },
      timeToFirstByte:        { type: String, default: null },
      firstInputDelay:        { type: String, default: null },
      pageSize:               { type: Number, default: 0 },
      requestCount:           { type: Number, default: 0 },
    },
    images: {
      totalImages:       { type: Number, default: 0 },
      unoptimizedImages: { type: Number, default: 0 },
      missingAlt:        { type: Number, default: 0 },
      hasLazyLoading:    { type: Boolean, default: false },
      nextGenFormats:    { type: Number, default: 0 },
      oversizedImages:   { type: Number, default: 0 },
    },
    security: {
      isHttps:           { type: Boolean, default: false },
      hasHsts:           { type: Boolean, default: false },
      hasMixedContent:   { type: Boolean, default: false },
      securityScore:     { type: Number, default: 0 },
    },
    seo: {
      titleLength:       { type: Number, default: 0 },
      metaDescLength:    { type: Number, default: 0 },
      h1Count:           { type: Number, default: 0 },
      hasCanonical:      { type: Boolean, default: false },
      hasStructuredData: { type: Boolean, default: false },
      hasOpenGraph:      { type: Boolean, default: false },
      hasAmpVersion:     { type: Boolean, default: false },
      hasRobotsTxt:      { type: Boolean, default: false },
      hasSitemap:        { type: Boolean, default: false },
      mobileFirstIndex:  { type: Boolean, default: false },
      seoScore:          { type: Number, default: 0 },
    },
    accessibility: {
      hasAriaLabels:      { type: Boolean, default: false },
      hasSkipLinks:       { type: Boolean, default: false },
      imagesHaveAlt:      { type: Boolean, default: false },
      formsHaveLabels:    { type: Boolean, default: false },
      colorContrastOk:    { type: Boolean, default: false },
      accessibilityScore: { type: Number, default: 0 },
    },
    pwa: {
      hasManifest:       { type: Boolean, default: false },
      hasServiceWorker:  { type: Boolean, default: false },
      isInstallable:     { type: Boolean, default: false },
      hasTouchIcons:     { type: Boolean, default: false },
      pwaScore:          { type: Number, default: 0 },
    },
  },

  scores: {
    overall:        { type: Number, default: 0 },
    performance:    { type: Number, default: 0 },
    responsive:     { type: Number, default: 0 },
    usability:      { type: Number, default: 0 },
    seo:            { type: Number, default: 0 },
    accessibility:  { type: Number, default: 0 },
    security:       { type: Number, default: 0 },
    pwa:            { type: Number, default: 0 },
  },

  issues:  { type: [IssueSchema], default: [] },

  aiInsights: {
    healthScore:   { type: Number, default: 0 },
    overallSummary:{ type: String, default: '' },
    whatWorksWell: { type: [String], default: [] },
    issuesSimple:  { type: [mongoose.Schema.Types.Mixed], default: [] },
    fixes:         { type: [mongoose.Schema.Types.Mixed], default: [] },
    priorityTable: { type: [mongoose.Schema.Types.Mixed], default: [] },
    provider:      { type: String, default: 'none' },
    generatedAt:   { type: Date, default: Date.now },
  },

  dataSourcesUsed: { type: [String], default: [] },
  status:  { type: String, enum: ['pending', 'completed', 'failed'], default: 'completed' },
  error:   { type: String, default: null },
  createdAt: { type: Date, default: Date.now },
}, { collection: 'mobile_analysis_reports', versionKey: false });

MobileFriendlinessSchema.index({ url: 1, createdAt: -1 });
module.exports = mongoose.model('MobileFriendliness', MobileFriendlinessSchema);